=== BestSoft/surgalt/diagrams/calendar/Documents/Xml/rich.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT CDs (CD*)>
<!ELEMENT CD (CDName, tracks, trackCR)>
<!ELEMENT CDName (#PCDATA)>
<!ELEMENT tracks (track+)>
<!ELEMENT track (Title, Artist, Genres, length)>
<!ELEMENT Genres (Genre)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Artist (#PCDATA)>
<!ELEMENT Genre (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT trackCR (#PCDATA)>

<!ATTLIST track trackNumber CDATA #REQUIRED>
<!ATTLIST CD id CDATA #REQUIRED>
<!ENTITY rnb "R and B">
<!ENTITY hh "Hip Hop">
<!ENTITY p "Pop">
<!ENTITY e "Electro">
<!ENTITY kp "KPop">
<!ENTITY j "Jazz">
<!ENTITY copyright "@Copyright">

=== BestSoft/surgalt/diagrams/calendar/Documents/Xml/DTDxml.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE CDs SYSTEM "rich.dtd">
    <CDs>
        <CD id="001">
        <CDName>UK Top 40 Singles</CDName>
        <tracks>
            <track trackNumber="1">
                <Title>Get Up (Rattle)</Title>
                <Artist>Bingo Players Feat Far East Movement</Artist>
                <Genres>
                    <Genre>&rnb;</Genre>
                </Genres>
                <length>00:02:47</length>
            </track>
            <track trackNumber="2">
                <Title>Radioactive</Title>
                <Artist>Rita Ora</Artist>
                <Genres>
                    <Genre>&e;</Genre>
                </Genres>
                <length>00:04:11</length>
            </track>
            <track trackNumber="3">
                <Title>Gangnam Style</Title>
                <Artist>PSY</Artist>
                <Genres>
                    <Genre>&kp;</Genre>
                </Genres>
                <length>00:03:39</length>
            </track>
        </tracks>
        <trackCR>&copyright;</trackCR>
        </CD>
    </CDs>

=== BestSoft/surgalt/sites/calendar.surgalt.info/DTDxml.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE CDs SYSTEM "rich.dtd">
    <CDs>
        <CD id="001">
        <CDName>UK Top 40 Singles</CDName>
        <tracks>
            <track trackNumber="1">
                <Title>Get Up (Rattle)</Title>
                <Artist>Bingo Players Feat Far East Movement</Artist>
                <Genres>
                    <Genre>&rnb;</Genre>
                </Genres>
                <length>00:02:47</length>
            </track>
            <track>
                <Title>Radioactive</Title>
                <Artist>Rita Ora</Artist>
                <Genres>
                    <Genre></Genre>
                </Genres>
                <length></length>
            </track>
            <track>
                <Number></Number>
                <Title></Title>
                <Artist></Artist>
                <Genres>
                    <Genre></Genre>
                </Genres>
                <length></length>
            </track>
            <track>
                <Number></Number>
                <Title></Title>
                <Artist></Artist>
                <Genres>
                    <Genre></Genre>
                </Genres>
                <length></length>
            </track>
        </tracks>
        <trackCR>&copyright</trackCR>
        </CD>
    </CDs>
